/**
 * Client automatically generated by SDKgen please do not edit this file manually
 * {@link https://sdkgen.app}
 */

import {ClientAbstract, CredentialsInterface, TokenStoreInterface, HttpRequest} from "sdkgen-client"
import {HttpBearer} from "sdkgen-client"
import {Anonymous} from "sdkgen-client"
import {ClientException, UnknownStatusCodeException} from "sdkgen-client";

import {CompletionsTag} from "./CompletionsTag";

export class Client extends ClientAbstract {
    public completions(): CompletionsTag
    {
        return new CompletionsTag(
            this.httpClient,
            this.parser
        );
    }



    public static build(token: string): Client
    {
        return new Client('https://api.openai.com/', new HttpBearer(token));
    }

    public static buildAnonymous(): Client
    {
        return new Client('https://api.openai.com/', new Anonymous());
    }
}
