/**
 * CompletionUsage automatically generated by SDKgen please do not edit this file manually
 * {@link https://sdkgen.app}
 */

import {CompletionTokensDetails} from "./CompletionTokensDetails";
import {PromptTokensDetails} from "./PromptTokensDetails";

export interface CompletionUsage {
    completion_tokens?: number
    prompt_tokens?: number
    total_tokens?: number
    completion_tokens_details?: CompletionTokensDetails
    prompt_tokens_details?: PromptTokensDetails
}

