/**
 * CompletionMessage automatically generated by SDKgen please do not edit this file manually
 * {@link https://sdkgen.app}
 */

import {CompletionMessageDeveloper} from "./CompletionMessageDeveloper";
import {CompletionMessageSystem} from "./CompletionMessageSystem";
import {CompletionMessageUser} from "./CompletionMessageUser";
import {CompletionMessageAssistant} from "./CompletionMessageAssistant";
import {CompletionMessageTool} from "./CompletionMessageTool";

export interface CompletionMessage {
    role?: string
    content?: Array<string>
}

