/**
 * CompletionDeleted automatically generated by SDKgen please do not edit this file manually
 * {@link https://sdkgen.app}
 */

export interface CompletionDeleted {
    object?: string
    id?: string
    deleted?: boolean
}

