/**
 * CompletionResponse automatically generated by SDKgen please do not edit this file manually
 * {@link https://sdkgen.app}
 */

import {CompletionChoice} from "./CompletionChoice";
import {CompletionUsage} from "./CompletionUsage";

export interface CompletionResponse {
    id?: string
    object?: string
    created?: number
    model?: string
    choices?: Array<CompletionChoice>
    usage?: CompletionUsage
    service_tier?: string
    system_fingerprint?: string
}

