/**
 * CompletionCollection automatically generated by SDKgen please do not edit this file manually
 * {@link https://sdkgen.app}
 */

import {CompletionResponse} from "./CompletionResponse";

export interface CompletionCollection {
    object?: string
    data?: Array<CompletionResponse>
    first_id?: string
    last_id?: string
    has_more?: boolean
}

