/**
 * CompletionTokensDetails automatically generated by SDKgen please do not edit this file manually
 * {@link https://sdkgen.app}
 */

export interface CompletionTokensDetails {
    accepted_prediction_tokens?: number
    audio_tokens?: number
    reasoning_tokens?: number
    rejected_prediction_tokens?: number
}

