/**
 * CompletionMessageAssistant automatically generated by SDKgen please do not edit this file manually
 * {@link https://sdkgen.app}
 */

import {CompletionMessage} from "./CompletionMessage";

export interface CompletionMessageAssistant extends CompletionMessage {
    audio?: string
    name?: string
    refusal?: string
    tool_calls?: Array<string>
}

