/**
 * CompletionMessageTool automatically generated by SDKgen please do not edit this file manually
 * {@link https://sdkgen.app}
 */

import {CompletionMessage} from "./CompletionMessage";

export interface CompletionMessageTool extends CompletionMessage {
    tool_call_id?: string
}

