/**
 * CompletionMessageSystem automatically generated by SDKgen please do not edit this file manually
 * {@link https://sdkgen.app}
 */

import {CompletionMessage} from "./CompletionMessage";

export interface CompletionMessageSystem extends CompletionMessage {
    name?: string
}

