/**
 * ErrorException automatically generated by SDKgen please do not edit this file manually
 * {@link https://sdkgen.app}
 */

import {KnownStatusCodeException} from "sdkgen-client"

import {Error} from "./Error";

export class ErrorException extends KnownStatusCodeException {

    public constructor(private payload: Error) {
        super('The server returned an error');
    }

    public getPayload(): Error {
        return this.payload;
    }

}
