/**
 * Error automatically generated by SDKgen please do not edit this file manually
 * {@link https://sdkgen.app}
 */

import {ErrorDetail} from "./ErrorDetail";

export interface Error {
    error?: ErrorDetail
}

