/**
 * PromptTokensDetails automatically generated by SDKgen please do not edit this file manually
 * {@link https://sdkgen.app}
 */

export interface PromptTokensDetails {
    audio_tokens?: number
    cached_tokens?: number
}

