/**
 * ResponseReasoning automatically generated by SDKgen please do not edit this file manually
 * {@link https://sdkgen.app}
 */

export interface ResponseReasoning {
    effort?: string
    summary?: string
}

