/**
 * ResponseResponseOutput automatically generated by SDKgen please do not edit this file manually
 * {@link https://sdkgen.app}
 */

import {ResponseResponseOutputMessage} from "./ResponseResponseOutputMessage";

export interface ResponseResponseOutput {
    type?: string
}

