/**
 * ResponseToolFunction automatically generated by SDKgen please do not edit this file manually
 * {@link https://sdkgen.app}
 */

import {ResponseTool} from "./ResponseTool";

export interface ResponseToolFunction extends ResponseTool {
    name?: string
    parameters?: any
    strict?: boolean
    type?: string
    description?: string
}

