/**
 * ResponseRequestInputMessage automatically generated by SDKgen please do not edit this file manually
 * {@link https://sdkgen.app}
 */

import {ResponseRequestInput} from "./ResponseRequestInput";

export interface ResponseRequestInputMessage extends ResponseRequestInput {
    content?: Array<string>
    role?: string
    type?: string
}

