/**
 * ResponseMCPTool automatically generated by SDKgen please do not edit this file manually
 * {@link https://sdkgen.app}
 */

export interface ResponseMCPTool {
    input_schema?: any
    name?: string
    annotations?: Record<string, string>
    description?: string
}

