/**
 * ResponseToolWebSearch automatically generated by SDKgen please do not edit this file manually
 * {@link https://sdkgen.app}
 */

import {ResponseTool} from "./ResponseTool";
import {ResponseToolWebSearchFilter} from "./ResponseToolWebSearchFilter";
import {ResponseToolWebSearchLocation} from "./ResponseToolWebSearchLocation";

export interface ResponseToolWebSearch extends ResponseTool {
    type?: string
    filters?: ResponseToolWebSearchFilter
    search_context_size?: string
    user_location?: ResponseToolWebSearchLocation
}

