/**
 * ResponseRequestInputFunctionCall automatically generated by SDKgen please do not edit this file manually
 * {@link https://sdkgen.app}
 */

import {ResponseRequestInput} from "./ResponseRequestInput";

/**
 * A tool call to run a function. See the function calling guide for more information.
 */
export interface ResponseRequestInputFunctionCall extends ResponseRequestInput {
    arguments?: string
    call_id?: string
    name?: string
    type?: string
    id?: string
    status?: string
}

