/**
 * ResponseRequest automatically generated by SDKgen please do not edit this file manually
 * {@link https://sdkgen.app}
 */

import {ResponseRequestInput} from "./ResponseRequestInput";
import {ResponsePrompt} from "./ResponsePrompt";
import {ResponseReasoning} from "./ResponseReasoning";
import {ResponseRequestText} from "./ResponseRequestText";
import {ResponseRequestTool} from "./ResponseRequestTool";

export interface ResponseRequest {
    background?: boolean
    conversation?: string
    include?: Array<string>
    input?: Array<ResponseRequestInput>
    instructions?: string
    max_output_tokens?: string
    max_tool_calls?: string
    metadata?: Record<string, string>
    model?: string
    parallel_tool_calls?: boolean
    previous_response_id?: string
    prompt?: ResponsePrompt
    prompt_cache_key?: string
    reasoning?: ResponseReasoning
    safety_identifier?: string
    service_tier?: string
    store?: boolean
    temperature?: number
    text?: ResponseRequestText
    tool_choice?: string
    tools?: Array<ResponseRequestTool>
    top_logprobs?: number
    top_p?: number
    truncation?: string
}

