/**
 * ResponseRequestTextFormatJsonSchema automatically generated by SDKgen please do not edit this file manually
 * {@link https://sdkgen.app}
 */

import {ResponseRequestTextFormat} from "./ResponseRequestTextFormat";

export interface ResponseRequestTextFormatJsonSchema extends ResponseRequestTextFormat {
    name?: string
    schema?: any
    type?: string
    description?: string
    strict?: boolean
}

