/**
 * ResponseResponseOutputMessage automatically generated by SDKgen please do not edit this file manually
 * {@link https://sdkgen.app}
 */

import {ResponseResponseOutput} from "./ResponseResponseOutput";

/**
 * An output message from the model.
 */
export interface ResponseResponseOutputMessage extends ResponseResponseOutput {
    content?: Array<string>
    id?: string
    role?: string
    status?: string
    type?: string
}

