/**
 * ResponseRequestToolFunction automatically generated by SDKgen please do not edit this file manually
 * {@link https://sdkgen.app}
 */

import {ResponseRequestTool} from "./ResponseRequestTool";

/**
 * Defines a function in your own code the model can choose to call.
 */
export interface ResponseRequestToolFunction extends ResponseRequestTool {
    name?: string
    parameters?: any
    strict?: boolean
    type?: string
    description?: string
}

