/**
 * ResponsePrompt automatically generated by SDKgen please do not edit this file manually
 * {@link https://sdkgen.app}
 */

export interface ResponsePrompt {
    id?: string
    variables?: Record<string, string>
    version?: string
}

