/**
 * ResponseRequestTool automatically generated by SDKgen please do not edit this file manually
 * {@link https://sdkgen.app}
 */

import {ResponseRequestToolFunction} from "./ResponseRequestToolFunction";

export interface ResponseRequestTool {
    type?: string
}

