/**
 * ResponseRequestInputFunctionCallOutput automatically generated by SDKgen please do not edit this file manually
 * {@link https://sdkgen.app}
 */

import {ResponseRequestInput} from "./ResponseRequestInput";

/**
 * The output of a function tool call.
 */
export interface ResponseRequestInputFunctionCallOutput extends ResponseRequestInput {
    call_id?: string
    output?: string
    type?: string
    id?: string
    status?: string
}

