/**
 * ResponseRequestText automatically generated by SDKgen please do not edit this file manually
 * {@link https://sdkgen.app}
 */

import {ResponseRequestTextFormat} from "./ResponseRequestTextFormat";

export interface ResponseRequestText {
    format?: ResponseRequestTextFormat
    verbosity?: string
}

