/**
 * ResponseResponse automatically generated by SDKgen please do not edit this file manually
 * {@link https://sdkgen.app}
 */

import {ResponseResponseError} from "./ResponseResponseError";
import {ResponseResponseOutput} from "./ResponseResponseOutput";

export interface ResponseResponse {
    created_at?: number
    error?: ResponseResponseError
    id?: string
    incomplete_details?: string
    object?: string
    output?: Array<ResponseResponseOutput>
    previous_response_id?: string
}

