/**
 * ResponseTextFormatText automatically generated by SDKgen please do not edit this file manually
 * {@link https://sdkgen.app}
 */

import {ResponseTextFormat} from "./ResponseTextFormat";

export interface ResponseTextFormatText extends ResponseTextFormat {
    type?: string
}

