/**
 * ResponseRequest automatically generated by SDKgen please do not edit this file manually
 * {@link https://sdkgen.app}
 */

import {ResponseRequestConversation} from "./ResponseRequestConversation";
import {ResponsePrompt} from "./ResponsePrompt";
import {ResponseReasoning} from "./ResponseReasoning";
import {ResponseText} from "./ResponseText";
import {ResponseTool} from "./ResponseTool";

export interface ResponseRequest {
    background?: boolean
    conversation?: ResponseRequestConversation
    include?: Array<string>
    input?: string
    instructions?: string
    max_output_tokens?: string
    max_tool_calls?: string
    metadata?: Record<string, string>
    model?: string
    parallel_tool_calls?: boolean
    previous_response_id?: string
    prompt?: ResponsePrompt
    prompt_cache_key?: string
    reasoning?: ResponseReasoning
    safety_identifier?: string
    service_tier?: string
    store?: boolean
    temperature?: number
    text?: ResponseText
    tool_choice?: string
    tools?: Array<ResponseTool>
    top_logprobs?: number
    top_p?: number
    truncation?: string
}

