/**
 * ResponseRequestText automatically generated by SDKgen please do not edit this file manually
 * {@link https://sdkgen.app}
 */

export interface ResponseRequestText {
    format?: string
    verbosity?: string
}

