/**
 * ResponseTextFormat automatically generated by SDKgen please do not edit this file manually
 * {@link https://sdkgen.app}
 */

import {ResponseTextFormatJsonSchema} from "./ResponseTextFormatJsonSchema";
import {ResponseTextFormatText} from "./ResponseTextFormatText";

export interface ResponseTextFormat {
    type?: string
}

