/**
 * ResponseRequestInputMcpListTools automatically generated by SDKgen please do not edit this file manually
 * {@link https://sdkgen.app}
 */

import {ResponseRequestInput} from "./ResponseRequestInput";
import {ResponseMCPTool} from "./ResponseMCPTool";

/**
 * A list of tools available on an MCP server.
 */
export interface ResponseRequestInputMcpListTools extends ResponseRequestInput {
    id?: string
    server_label?: string
    tools?: Array<ResponseMCPTool>
    error?: string
    type?: string
}

