/**
 * ResponseTextFormatJsonSchema automatically generated by SDKgen please do not edit this file manually
 * {@link https://sdkgen.app}
 */

import {ResponseTextFormat} from "./ResponseTextFormat";

export interface ResponseTextFormatJsonSchema extends ResponseTextFormat {
    name?: string
    schema?: any
    type?: string
    description?: string
    strict?: boolean
}

