/**
 * ResponseRequestTextFormatText automatically generated by SDKgen please do not edit this file manually
 * {@link https://sdkgen.app}
 */

import {ResponseRequestTextFormat} from "./ResponseRequestTextFormat";

export interface ResponseRequestTextFormatText extends ResponseRequestTextFormat {
    type?: string
}

