/**
 * ResponseTool automatically generated by SDKgen please do not edit this file manually
 * {@link https://sdkgen.app}
 */

import {ResponseToolFunction} from "./ResponseToolFunction";
import {ResponseToolMCP} from "./ResponseToolMCP";
import {ResponseToolWebSearch} from "./ResponseToolWebSearch";

export interface ResponseTool {
    type?: string
}

