/**
 * ResponseRequestInput automatically generated by SDKgen please do not edit this file manually
 * {@link https://sdkgen.app}
 */

import {ResponseRequestInputFunctionCall} from "./ResponseRequestInputFunctionCall";
import {ResponseRequestInputFunctionCallOutput} from "./ResponseRequestInputFunctionCallOutput";
import {ResponseRequestInputMessage} from "./ResponseRequestInputMessage";

/**
 * An item representing part of the context for the response to be generated by the model. Can contain text, images, and audio inputs, as well as previous assistant responses and tool call outputs.
 */
export interface ResponseRequestInput {
    type?: string
}

