/**
 * ResponseToolWebSearchLocation automatically generated by SDKgen please do not edit this file manually
 * {@link https://sdkgen.app}
 */

export interface ResponseToolWebSearchLocation {
    city?: string
    country?: string
    region?: string
    timezone?: string
    type?: string
}

