/**
 * ResponseToolMCP automatically generated by SDKgen please do not edit this file manually
 * {@link https://sdkgen.app}
 */

import {ResponseTool} from "./ResponseTool";

export interface ResponseToolMCP extends ResponseTool {
    server_label?: string
    type?: string
    allowed_tools?: Array<string>
    authorization?: string
    connector_id?: string
    headers?: Record<string, string>
    require_approval?: string
    server_description?: string
    server_url?: string
}

