/**
 * ResponseRequestTextFormat automatically generated by SDKgen please do not edit this file manually
 * {@link https://sdkgen.app}
 */

import {ResponseRequestTextFormatJsonSchema} from "./ResponseRequestTextFormatJsonSchema";
import {ResponseRequestTextFormatText} from "./ResponseRequestTextFormatText";

export interface ResponseRequestTextFormat {
    type?: string
}

