/**
 * ResponseText automatically generated by SDKgen please do not edit this file manually
 * {@link https://sdkgen.app}
 */

import {ResponseTextFormat} from "./ResponseTextFormat";

export interface ResponseText {
    format?: ResponseTextFormat
    verbosity?: string
}

