/**
 * ResponseResponseOutputFunctionCall automatically generated by SDKgen please do not edit this file manually
 * {@link https://sdkgen.app}
 */

import {ResponseResponseOutput} from "./ResponseResponseOutput";

export interface ResponseResponseOutputFunctionCall extends ResponseResponseOutput {
    arguments?: string
    call_id?: string
    name?: string
    type?: string
    id?: string
    status?: string
}

